---
title: "Title EDA - Covid-19"
---

# Setup
## Packages
```{r, message = FALSE}
library(tidyverse)
library(tidycovid19)
library(zoo)
library(knitr)
library(kableExtra)
```

## Data
```{r}
df <- download_merged_data(cached = TRUE, silent = TRUE) %>%
  group_by(country) %>%
  mutate(
    # New daily confirmed cases
    new_confirmed = confirmed - lag(confirmed),
    # New daily confirmed cases per capita
    new_confirmed_pc = new_confirmed / population,
    # Cum confirmed cases per capita
    confirmed_pc = confirmed / population,
    
    # New daily deaths
    new_deaths = deaths - lag(deaths),
    # New daily deaths per capita
    new_deaths_pc = new_deaths / population,
    # Cum deaths per capita
    deaths_pc = deaths / population,
    
    # 7 Day moving averages for confirmed, deaths, and per capita
    ave_7d_new_confirmed = rollmean(new_confirmed, 7, na.pad=TRUE, align="right"),
    ave_7d_new_deaths = rollmean(new_deaths, 7, na.pad=TRUE, align="right"),
    ave_7d_new_confirmed_pc = rollmean(new_confirmed_pc, 7, na.pad=TRUE, align="right"),
    ave_7d_new_deaths_pc = rollmean(new_deaths_pc, 7, na.pad=TRUE, align="right")
  ) %>%
  ungroup()

glimpse(df)
```
## Variable Definitions
```{r}
var_d <- tidycovid19_variable_definitions %>%
  select(var_name, var_def)

kable(var_d) %>% 
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", height = "300px")
```


# EDA - Exploratory Data Analysis

## Global Numbers
### Data
```{r}
global_df <- df %>%
  group_by(date) %>%
  summarize(
    global_confirmed = sum(confirmed, na.rm = TRUE), 
    global_deaths = sum(deaths, na.rm = TRUE),
    ) %>%
  mutate(
    global_new_confirmed = global_confirmed - lag(global_confirmed),
    global_new_deaths = global_deaths - lag(global_deaths),
    global_ave_7d_new_deaths = rollmean(global_new_deaths, 7, na.pad=TRUE, align="right"),
    global_ave_7d_new_confirmed = rollmean(global_new_confirmed, 7, na.pad=TRUE, align="right")
  )


```

### Global Confirmed Cases
```{r}
ggplot(global_df, aes(x = date)) +
  geom_line(aes(y = global_new_confirmed), alpha = 0.1) +
  geom_line(aes(y = global_ave_7d_new_confirmed), color = "red") +
  labs(title = "7-day rolling mean\nGlobal daily deaths", x = "", y = "")
```

### Global Deaths
```{r}
ggplot(global_df, aes(x = date)) +
  geom_line(aes(y = global_new_deaths), alpha = 0.1) +
  geom_line(aes(y = global_ave_7d_new_deaths), color = "red") +
  labs(title = "7-day rolling mean\nGlobal daily deaths", x = "", y = "")
```

## Country Specific Numbers
#high <- df %>%
#  group_by(country) %>%
  


# Modeling

